<template>
  <div class="guide-body">

    <section class="guide-section">
      <p>
        <strong>Entropy</strong> measures how unpredictable a password is, in bits. It is not a measure of how
        complicated a password looks to a human — it is a measure of how many attempts a brute-force attacker
        would need on average to guess it, assuming every character was chosen uniformly at random from a
        known set of possibilities.
      </p>
      <p>
        The formula is simple: <code>entropy = length × log₂(charset size)</code>. Each bit of entropy doubles
        the number of possible passwords, so entropy grows linearly with length but only logarithmically with
        how many different characters are allowed — length matters more than character variety.
      </p>
    </section>

    <section class="guide-section">
      <h2>Charset size drives less than you'd think</h2>
      <table class="cheat-table">
        <thead><tr><th>Character set</th><th>Size</th><th>Bits per character</th></tr></thead>
        <tbody>
          <tr><td>Lowercase only (a–z)</td><td>26</td><td>4.7</td></tr>
          <tr><td>Lower + uppercase (a–z, A–Z)</td><td>52</td><td>5.7</td></tr>
          <tr><td>Lower + upper + digits</td><td>62</td><td>5.95</td></tr>
          <tr><td>Full printable ASCII (+ symbols)</td><td>~94</td><td>6.55</td></tr>
        </tbody>
      </table>
      <p>
        Going from lowercase-only to the full printable set roughly adds two more bits per character — going
        from 8 characters to 16 characters adds 8 more characters' worth of bits entirely. Length wins.
      </p>
    </section>

    <section class="guide-section">
      <h2>What entropy looks like in practice</h2>
      <table class="cheat-table">
        <thead><tr><th>Password</th><th>Entropy</th><th>Time to crack at 1 billion guesses/sec*</th></tr></thead>
        <tbody>
          <tr><td>8 chars, lowercase only</td><td>37.6 bits</td><td>~1.7 minutes</td></tr>
          <tr><td>8 chars, mixed case + digits</td><td>47.6 bits</td><td>~1.3 days</td></tr>
          <tr><td>12 chars, mixed case + digits</td><td>71.5 bits</td><td>~51,000 years</td></tr>
          <tr><td>16 chars, full printable set</td><td>104.9 bits</td><td>~5.9 × 10¹⁴ years</td></tr>
        </tbody>
      </table>
      <p class="footnote">
        * Illustrative only. "Guesses per second" varies by orders of magnitude depending on the hashing
        algorithm, not whether the password is salted: a modern GPU can try billions of guesses per second
        against a fast hash like raw MD5 or SHA-256, but only a few hundred per second against a properly
        configured bcrypt or Argon2 hash. Salting stops one precomputed table from cracking every account at
        once — it has no effect on how fast a single already-captured hash can be attacked. Entropy tells you
        the size of the search space — it says nothing about how fast an attacker can search it.
      </p>
    </section>

    <section class="guide-section">
      <h2>How many bits is enough?</h2>
      <table class="cheat-table">
        <thead><tr><th>Entropy</th><th>Rating</th></tr></thead>
        <tbody>
          <tr><td>Under 40 bits</td><td>Weak</td></tr>
          <tr><td>40–59 bits</td><td>Fair</td></tr>
          <tr><td>60–79 bits</td><td>Good</td></tr>
          <tr><td>80+ bits</td><td>Strong</td></tr>
        </tbody>
      </table>
      <p>
        These are the same cutoffs this site's
        <NuxtLink to="/tools/password-generator" class="guide-inline-link">password generator</NuxtLink>
        uses for its live strength meter, so the label it shows you maps directly back to the entropy math above.
      </p>
    </section>

    <section class="guide-section">
      <h2>Where the math breaks down: humans aren't random</h2>
      <p>
        The entropy formula assumes every character is chosen independently and uniformly at random. A
        password a person invents rarely is. <code>P@ssw0rd123!</code> is 12 characters across the full
        character set and scores well on paper, but it follows an extremely common substitution pattern
        (<code>@</code> for <code>a</code>, <code>0</code> for <code>o</code>) that password-cracking
        dictionaries specifically test for. Its real-world resistance is far below its theoretical entropy.
      </p>
      <p>
        This is why modern guidance (including <a href="https://pages.nist.gov/800-63-4/sp800-63b.html" target="_blank" rel="noopener">NIST SP 800-63B</a>)
        has shifted away from mandating character-class complexity rules and toward encouraging length —
        random passphrases or, better, passwords generated by a tool that actually samples uniformly at
        random rather than a human trying to "look random."
      </p>
    </section>

    <section class="guide-section">
      <h2>What actually protects an account</h2>
      <ul>
        <li><strong>Length over complexity</strong> — a longer password with a smaller charset often beats a shorter one with every character class forced in.</li>
        <li><strong>Uniqueness per site</strong> — entropy is irrelevant if the same password is reused and one of the sites using it is breached. Credential-stuffing attacks replay leaked username/password pairs against other sites, not brute-force guessing.</li>
        <li><strong>A password manager</strong> — the practical way to have both a genuinely random password and a different one per site, without memorizing any of them.</li>
        <li><strong>Two-factor authentication</strong> — makes a leaked or guessed password alone insufficient, independent of how strong it was.</li>
      </ul>
      <p>
        A tool like this site's
        <NuxtLink to="/tools/password-generator" class="guide-inline-link">password generator</NuxtLink>
        uses the browser's cryptographically secure random number generator to sample uniformly at random from
        the selected character set, so the entropy math actually applies — unlike a password a person invents
        under the illusion of randomness.
      </p>
    </section>

  </div>
</template>

<style scoped>
.footnote { font-size: 12px; color: var(--c-t4); line-height: 1.6; }
</style>
